# Generated by Django 5.0.1 on 2024-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attachmentPost',
            fields=[
                ('company_name', models.CharField(null=True)),
                ('company_description', models.CharField(null=True)),
                ('company_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(null=True)),
                ('attachement_positions', models.CharField(null=True)),
                ('physical_address', models.CharField(null=True)),
            ],
        ),
    ]
