# Generated by Django 5.0.1 on 2024-04-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentpost',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
