# Generated by Django 5.0.1 on 2024-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_companysignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='registered',
            fields=[
                ('full_name', models.CharField(null=True)),
                ('phone_number', models.CharField(null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('physical_address', models.CharField(null=True)),
                ('college_name', models.CharField(null=True)),
                ('course_name', models.CharField(null=True)),
                ('year_of_study', models.CharField(null=True)),
                ('graduation_date', models.CharField(null=True)),
                ('learning_objectives', models.CharField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('company_name', models.CharField(null=True)),
                ('company_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companysignup',
            name='id',
        ),
        migrations.AlterField(
            model_name='companysignup',
            name='email',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
