# Generated by Django 5.0.1 on 2024-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_registered_remove_companysignup_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminsignup',
            fields=[
                ('last_name', models.CharField(null=True)),
                ('first_name', models.CharField(null=True)),
                ('username', models.CharField(null=True)),
                ('email', models.CharField(primary_key=True, serialize=False)),
                ('password', models.CharField(null=True)),
            ],
        ),
    ]
