# Generated by Django 5.0.1 on 2024-05-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_adminsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='approved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(null=True)),
                ('phone_number', models.CharField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('physical_address', models.CharField(null=True)),
                ('college_name', models.CharField(null=True)),
                ('course_name', models.CharField(null=True)),
                ('year_of_study', models.CharField(null=True)),
                ('graduation_date', models.CharField(null=True)),
                ('learning_objectives', models.CharField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('company_name', models.CharField(null=True)),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('attachment_status', models.CharField(null=True)),
            ],
        ),
    ]
