# Generated by Django 5.0.1 on 2024-05-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_registered_attachment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approved',
            old_name='attachment_status',
            new_name='ttachment_status',
        ),
    ]
