# Generated by Django 5.0.1 on 2024-05-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_attachment_status_approved_ttachment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approved',
            old_name='ttachment_status',
            new_name='attachment_status',
        ),
    ]
